version: 0.2

phases:
  build:
    commands:
      - echo Entered Into Build Phase
      - mvn clean package
      
  post_build:
    commands:
      - echo Build Completed Successfully
      
artifacts:
  files:
    - target/awsems.jar
  discard-paths: yes
