#spring.datasource.url=jdbc:mysql://database-2.cdmithirw8jv.ap-south-1.rds.amazonaws.com:3306/employee
#spring.datasource.username=admin
#spring.datasource.password=12345678
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  jpa:
    show-sql: true
  h2:
    console:
      enabled: true
